# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 15:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='allowed_users',
            field=models.ManyToManyField(null=True, related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
